version: '3.7'
services:
  mosquitto:
    image: "eclipse-mosquitto"
    ports:
      - "8883:8883"
      - "1883:1883"
    volumes: 
      - ./docker_config:/mosquitto/config
  publisher:
    build: ./publisher
  subscriber:
    build: ./subscriber
    volumes: 
      - ./output_db:/sub/output_db
    
