apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        machinetype: raspi
      containers:
      - name: nginx
        image: nginx:1.15.8-alpine
        ports:
        - containerPort: 80
